Repository ShallWeProject/ShallWeProject_iOS, pull requests merged in 2023-12, with the labels that each got.

#8 [Feat] #5 - 경험상세페이지 UI 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Literals/ColorLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Protocols/UICollectionViewRegisterable.swift
  ShallWe/ShallWe/Global/Protocols/UITableViewRegisterable.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7@3x.png
  ShallWe/ShallWe/Presentation/ExperienceDetail/Cell/ExperienceImageCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceDetail/Cell/ExplainTableViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceDetail/View/ExperienceDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceDetail/View/ExplainDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceDetail/View/GuideDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceDetail/ViewController/ExperienceDetailViewController.swift
Labels: 🌱 Feat, 🐰 아라

#10 [Feat] #3 - 홈 뷰 UI 및 기능 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Extension/UICollectionView+.swift
  ShallWe/ShallWe/Global/Literals/ImageLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad1.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad1.imageset/ad1.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad1.imageset/ad1@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad1.imageset/ad1@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad2.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad2.imageset/ad2.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad2.imageset/ad2@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/ad2.imageset/ad2@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/logo/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/logo/logo_shallwe.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/logo/logo_shallwe.imageset/Shall We.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_birthday.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_birthday.imageset/Group 34933.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_birthday.imageset/Group 34933@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_birthday.imageset/Group 34933@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_grade.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_grade.imageset/Group 34936.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_grade.imageset/Group 34936@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_grade.imageset/Group 34936@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_lover.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_lover.imageset/Group 34934.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_lover.imageset/Group 34934@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_lover.imageset/Group 34934@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_marriage.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_marriage.imageset/Group 34937.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_marriage.imageset/Group 34937@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_marriage.imageset/Group 34937@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_parents.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_parents.imageset/Group 34935.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_parents.imageset/Group 34935@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/recommend category/img_parents.imageset/Group 34935@3x.png
  ShallWe/ShallWe/Presentation/Common/Base/BaseView.swift
  ShallWe/ShallWe/Presentation/Common/Base/BaseViewController.swift
  ShallWe/ShallWe/Presentation/Common/Components/CustomNavigationBar.swift
  ShallWe/ShallWe/Presentation/Home/Cells/ExperienceCell.swift
  ShallWe/ShallWe/Presentation/Home/Cells/HomeGalleryCell.swift
  ShallWe/ShallWe/Presentation/Home/Cells/HomePopularCategoryCell.swift
  ShallWe/ShallWe/Presentation/Home/Cells/HomeRecommendCell.swift
  ShallWe/ShallWe/Presentation/Home/HomeViewController.swift
  ShallWe/ShallWe/Presentation/Home/Models/GalleryModel.swift
  ShallWe/ShallWe/Presentation/Home/Models/HomeExperienceModel.swift
  ShallWe/ShallWe/Presentation/Home/Models/PopularCategoryModel.swift
  ShallWe/ShallWe/Presentation/Home/Models/RecommendModel.swift
  ShallWe/ShallWe/Presentation/Home/ViewControllers/HomeViewController.swift
  ShallWe/ShallWe/Presentation/Home/ViewModels/HomeViewModel.swift
  ShallWe/ShallWe/Presentation/Home/Views/GalleryFooterView.swift
  ShallWe/ShallWe/Presentation/Home/Views/HomeHeaderView.swift
  ShallWe/ShallWe/Presentation/Home/Views/HomeView.swift
  ShallWe/ShallWe/Presentation/Home/Views/SearchView.swift
Labels: 🌱 Feat, 🐸 정

#12 [Fix] #11 - svg 이미지 파일 반영
  .gitignore
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_alert.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_alert.imageset/ic_alert.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_down.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_down.imageset/ic_arrow_down.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_down_small.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_down_small.imageset/ic_arrow_down_small.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_left.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_left.imageset/ic_arrow_left.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_up.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_arrow_up.imageset/ic_arrow_up.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_book.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_book.imageset/ic_book.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_activated.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_activated.imageset/ic_check_activated.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_default.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_default.imageset/ic_check_default.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_round_activated.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_round_activated.imageset/ic_check_round_activated.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_round_default.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_check_round_default.imageset/ic_check_round_default.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_delete.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_delete.imageset/ic_delete.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_gift.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_gift.imageset/ic_gift.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_left_calender-1.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_left_calender-1.imageset/ic_left_calender-1.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_left_calender.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_left_calender.imageset/ic_left_calender.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_minus.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_minus.imageset/ic_minus.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_plus.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_plus.imageset/ic_plus.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_plus_circle.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_plus_circle.imageset/ic_plus_circle.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_right_calender-1.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_right_calender-1.imageset/ic_right_calender-1.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_right_calender.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_right_calender.imageset/ic_right_calender.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_search.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_search.imageset/ic_search.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_search_colored.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Icon/ic_search_colored.imageset/ic_search_colored.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example.imageset/예시2@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/example2.imageset/image 7@3x.png
Labels: 🎈 Fix, 🐸 정

#14 [Feature] 로그인/회원가입 UI 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Application/SceneDelegate.swift
  ShallWe/ShallWe/Global/Literals/ColorLiterals.swift
  ShallWe/ShallWe/Global/Literals/ImageLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/firework.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/firework.imageset/img_firework.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/firework.imageset/img_firework@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/firework.imageset/img_firework@3x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/kakaoLoginIcon.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/kakaoLoginIcon.imageset/kakaoLoginIcon.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/shallWeLogo.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Auth/shallWeLogo.imageset/shallwe_logo_all.svg
  ShallWe/ShallWe/Global/Resource/Base.lproj/LaunchScreen.storyboard
  ShallWe/ShallWe/Presentation/Auth/Util/Enums.swift
  ShallWe/ShallWe/Presentation/Auth/View/AuthCompletionView.swift
  ShallWe/ShallWe/Presentation/Auth/View/AuthHeaderView.swift
  ShallWe/ShallWe/Presentation/Auth/View/LoginView.swift
  ShallWe/ShallWe/Presentation/Auth/View/PhoneNumberVerificationView.swift
  ShallWe/ShallWe/Presentation/Auth/View/ProfileEntryView.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/LoginCompletionViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/LoginViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/PhoneNumberVerificationViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/ProfileEntryViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/SignUpCompletionViewController.swift
  ShallWe/ShallWe/Presentation/Common/Components/CustomButton.swift
  ShallWe/ShallWe/Presentation/Common/Components/CustomTextFieldView.swift
Labels: 🌱 Feat, 🐶 나연

#16 [Feature] #9 - 경험선물페이지 UI 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Extension/UITextField+.swift
  ShallWe/ShallWe/Global/Literals/FontLiterals.swift
  ShallWe/ShallWe/Global/Literals/ImageLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/초대장.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/초대장@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/초대장@3x.png
  ShallWe/ShallWe/Presentation/Common/Components/CustomNavigationBar.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/Cell/ExperienceImageCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/Cell/ExplainTableViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/ExperienceDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/ExplainDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/GuideDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/ViewController/ExperienceDetailViewController.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/Cell/TimeCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/View/ExperienceGiftView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/ViewController/ExperienceGiftViewController.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceLetter/View/ExperienceLetterView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceLetter/ViewController/ExperienceLetterViewController.swift
Labels: 🌱 Feat, 🐰 아라

#18 [Hotfix] #17 - 머지충돌해결
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/letter.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/letter@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Img/letter.imageset/letter@3x.png
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/Cell/TimeCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/View/ExperienceGiftView.swift
Labels: 🎈 Fix, 🐰 아라
