Repository ShallWeProject/ShallWeProject_iOS, pull requests merged in 2024-02, with the labels that each got.

#35 [Fix] #32 - 카테고리 리스트 뷰 기능 수정
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Presentation/Main/Category/ViewControllers/CategoryViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Cells/SortHalfModalCell.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/ExperiencePageVC.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Category/CategoryListViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/ExperienceViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/RecommendListViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeCategoryView.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeExperienceView.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeRecommendView.swift
  ShallWe/ShallWe/Presentation/Main/Home/ViewControllers/HomeViewController.swift
Labels: 🎈 Fix, 🐸 정

#38 [Setting] #37 - 서버 초기세팅
  .gitignore
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Data/Home/ExperienceGiftResponseDto.swift
  ShallWe/ShallWe/Network/Base/APIConstant.swift
  ShallWe/ShallWe/Network/Base/URLConstant.swift
Labels: ⚙️ Setting, 🐸 정

#36 [Setting] #34 - 개발자 계정 세팅
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe.xcodeproj/xcshareddata/xcschemes/ShallWe.xcscheme
  ShallWe/ShallWe/Info.plist
Labels: ⚙️ Setting, 🐰 아라

#42 [Feat] #39 - 홈 뷰 API 연결
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Application/TokenManager.swift
  ShallWe/ShallWe/Data/DTO.swift
  ShallWe/ShallWe/Data/Home/ExperienceGiftResponseDto.swift
  ShallWe/ShallWe/Network/API/API.swift
  ShallWe/ShallWe/Network/API/Home/HomeAPI.swift
  ShallWe/ShallWe/Network/APIService/APIService.swift
  ShallWe/ShallWe/Network/APIService/Home/HomeTarget.swift
  ShallWe/ShallWe/Network/Base/BaseTargetType.swift
  ShallWe/ShallWe/Network/Base/GeneralResponse.swift
  ShallWe/ShallWe/Presentation/Main/Home/ViewModels/HomeViewModel.swift
Labels: 🌱 Feat, 🐸 정

#44 [Feat] #41 - 경험 상세페이지 API 연결 및 MVVM 구조로 리팩토링
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Data/Experience/ExperienceDetailResponseDto.swift
  ShallWe/ShallWe/Network/API/Experience/ExperienceAPI.swift
  ShallWe/ShallWe/Network/APIService/Experience/ExperienceTarget.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/Cell/ExperienceImageCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/Cell/ExplainTableViewCell.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/ExperienceDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/ExplainDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/GuideDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/ViewController/ExperienceDetailViewController.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/ViewModel/ExperienceDetailViewModel.swift
Labels: ☁️ Refactor, 🌱 Feat, 🐰 아라
