Repository ShallWeProject/ShallWeProject_iOS, pull requests merged in 2024-01, with the labels that each got.

#15 [Feat] #13 - 상황별추천 경험 뷰 구현
  .gitignore
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ShallWe/ShallWe/Global/Extension/UIButton+.swift
  ShallWe/ShallWe/Global/Literals/SizeLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Presentation/Common/Base/BaseView.swift
  ShallWe/ShallWe/Presentation/Common/Components/CustomNavigationBar.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Cells/HomeMenuCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperiencePageVC.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperienceType.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/HomeRecommendViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/PageViewControllers/BirthViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/PageViewControllers/GradeViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/PageViewControllers/LoverViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/PageViewControllers/MarriageViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/PageViewControllers/ParentsViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewModels/HomeExperienceListViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewModels/HomeExperienceViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/ActivateDropDownAlert.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/CustomDropDownButton.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/ExperienceHeader.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeExperienceListView.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeRecommendView.swift
  ShallWe/ShallWe/Presentation/Main/Home/Cells/HomeExperienceCell.swift
  ShallWe/ShallWe/Presentation/Main/Home/Cells/HomeGalleryCell.swift
  ShallWe/ShallWe/Presentation/Main/Home/Cells/HomePopularCategoryCell.swift
  ShallWe/ShallWe/Presentation/Main/Home/Cells/HomeRecommendCell.swift
  ShallWe/ShallWe/Presentation/Main/Home/Models/GalleryModel.swift
  ShallWe/ShallWe/Presentation/Main/Home/Models/HomeExperienceModel.swift
  ShallWe/ShallWe/Presentation/Main/Home/Models/PopularCategoryModel.swift
  ShallWe/ShallWe/Presentation/Main/Home/Models/RecommendModel.swift
  ShallWe/ShallWe/Presentation/Main/Home/ViewControllers/HomeViewController.swift
  ShallWe/ShallWe/Presentation/Main/Home/ViewModels/HomeViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Home/Views/GalleryFooterView.swift
  ShallWe/ShallWe/Presentation/Main/Home/Views/HomeHeaderView.swift
  ShallWe/ShallWe/Presentation/Main/Home/Views/HomeView.swift
  ShallWe/ShallWe/Presentation/Main/Home/Views/SearchView.swift
  ShallWe/ShallWe/Presentation/TabBar/TabBarController.swift
Labels: 🌱 Feat, 🐸 정

#20 [Feature] #19 - 카테고리 뷰 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Application/SceneDelegate.swift
  ShallWe/ShallWe/Global/Extension/UIViewController+.swift
  ShallWe/ShallWe/Global/Literals/ImageLiterals.swift
  ShallWe/ShallWe/Global/Literals/SizeLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_album.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_album.imageset/album.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_baking.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_baking.imageset/baking.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_craft.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_craft.imageset/craft.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_culture.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_culture.imageset/culture.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_faq.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_faq.imageset/faq.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_getGift.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_getGift.imageset/ic_getGift.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_mail.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_mail.imageset/mail.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_outdoor.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_outdoor.imageset/outdoor.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_sendGift.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_sendGift.imageset/sendGift.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_sport.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/Home/Category/ic_sport.imageset/sport.svg
  ShallWe/ShallWe/Presentation/Category/CategoryViewController.swift
  ShallWe/ShallWe/Presentation/Category/Views/CategoryViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperiencePageVC.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperienceType.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/HomeExperienceViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/BakingViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/CraftViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/CultureViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/OutdoorViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/SportViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/HomeRecommendViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/BirthViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/GradeViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/LoverViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/MarriageViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/ParentsViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewModels/HomeExperienceViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeExperienceView.swift
  ShallWe/ShallWe/Presentation/Main/Home/Views/HomeView.swift
  ShallWe/ShallWe/Presentation/TabBar/TabBarController.swift
Labels: 🌱 Feat, 🐸 정

#23 [Feature] #21 - 검색 뷰 및 기능 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Presentation/Main/Category/ViewControllers/CategoryViewController.swift
  ShallWe/ShallWe/Presentation/Main/Home/ViewControllers/HomeViewController.swift
  ShallWe/ShallWe/Presentation/Main/Search/Cells/RecentSearchCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/Main/Search/Models/RecentSearchModel.swift
  ShallWe/ShallWe/Presentation/Main/Search/ViewControllers/SearchViewController.swift
  ShallWe/ShallWe/Presentation/Main/Search/ViewModels/SearchViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Search/Views/RecentSearchView.swift
  ShallWe/ShallWe/Presentation/Main/Search/Views/SearchResultView.swift
  ShallWe/ShallWe/Presentation/Main/Search/Views/SearchTextFieldView.swift
Labels: 🌱 Feat, 🐸 정

#25 [Feature] #6 - 회원가입/로그인 UI 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Presentation/Auth/View/AgreementOfTermsView.swift
  ShallWe/ShallWe/Presentation/Auth/View/AuthCompletionView.swift
  ShallWe/ShallWe/Presentation/Auth/View/ProfileEntryView.swift
  ShallWe/ShallWe/Presentation/Auth/View/TermsDetailsPopUpView.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/AgreementToTermsViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/PhoneNumberVerificationViewController.swift
  ShallWe/ShallWe/Presentation/Auth/ViewController/TermsDetailsPopUpViewController.swift
Labels: 🌱 Feat, 🐶 나연

#27 [Feat] #24 - 정렬 기능 바텀시트 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Presentation/Main/Category/ViewControllers/CategoryViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Cells/SortHalfModalCell.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/ExperiencePageVC.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperiencePageVC.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/HomeExperienceType.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Models/SortModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Category/HomeCategoryViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/ExperienceViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/BakingViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/CraftViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/CultureViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/OutdoorViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/PageViewControllers/SportViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Experience/SortHalfModal.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/HomeRecommendViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/BirthViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/GradeViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/LoverViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/MarriageViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewControllers/Recommend/PageViewControllers/ParentsViewController.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewModels/HomeExperienceListViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/ViewModels/HomeExperienceViewModel.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/ActivateDropDownAlert.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/CustomDropDownButton.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/ExperienceHeader.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeCategoryView.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeExperienceListView.swift
  ShallWe/ShallWe/Presentation/Main/Experience/Views/HomeRecommendView.swift
Labels: 🌱 Feat, 🐸 정

#29 [Feat] #28 - 마이페이지뷰 UI 구현
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Global/Literals/FontLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_calendar.imageset/Calendar_light 1.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_calendar.imageset/Calendar_light 2.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_calendar.imageset/Calendar_light.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_calendar.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_letter.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_letter.imageset/emojione_love-letter 1.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_letter.imageset/emojione_love-letter 2.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_letter.imageset/emojione_love-letter.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_time.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_time.imageset/Time_light 1.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_time.imageset/Time_light 2.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/ic_time.imageset/Time_light.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/img_background.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/img_background.imageset/Group 34919.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/img_background.imageset/Group 34919@2x.png
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/MyPage/img_background.imageset/Group 34919@3x.png
  ShallWe/ShallWe/Global/Utils/MakeAlert.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/CompleteScene/View/CompleteView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/CompleteScene/ViewController/CompleteViewController.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceDetail/View/ExperienceDetailView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/View/ExperienceGiftView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceGift/ViewController/ExperienceGiftViewController.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceLetter/View/ExperienceLetterView.swift
  ShallWe/ShallWe/Presentation/ExperienceScene/ExperienceLetter/ViewController/ExperienceLetterViewController.swift
  ShallWe/ShallWe/Presentation/Mypage/Cells/MyPageReceiverCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/Mypage/Cells/MyPageSenderCollectionViewCell.swift
  ShallWe/ShallWe/Presentation/Mypage/Entity/MyPageReceiverEntity.swift
  ShallWe/ShallWe/Presentation/Mypage/Entity/MyPageSenderEntity.swift
  ShallWe/ShallWe/Presentation/Mypage/MypageViewController.swift
  ShallWe/ShallWe/Presentation/Mypage/ViewController/MyPageViewController.swift
  ShallWe/ShallWe/Presentation/Mypage/Views/MyPageReceiverView.swift
  ShallWe/ShallWe/Presentation/Mypage/Views/MyPageSenderView.swift
  ShallWe/ShallWe/Presentation/Mypage/Views/MyPageView.swift
  ShallWe/ShallWe/Presentation/TabBar/TabBarController.swift
Labels: 🌱 Feat, 🐰 아라

#31 [Feature] #26 - FAQ, 계정관리 화면 UI
  ShallWe/ShallWe.xcodeproj/project.pbxproj
  ShallWe/ShallWe/Application/SceneDelegate.swift
  ShallWe/ShallWe/Global/Extension/UILabel+.swift
  ShallWe/ShallWe/Global/Extension/UIView+.swift
  ShallWe/ShallWe/Global/Literals/FontLiterals.swift
  ShallWe/ShallWe/Global/Literals/ImageLiterals.swift
  ShallWe/ShallWe/Global/Literals/StringLiterals.swift
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/FAQ/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/FAQ/faq.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/FAQ/faq.imageset/faq.svg
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/FAQ/shallWeLogo_small.imageset/Contents.json
  ShallWe/ShallWe/Global/Resource/AssetCatalog/Image.xcassets/FAQ/shallWeLogo_small.imageset/shallWeLogo_small.svg
  ShallWe/ShallWe/Global/Resource/Font/AbhayaLibre-ExtraBold.ttf
  ShallWe/ShallWe/Global/Utils/MakeAlert.swift
  ShallWe/ShallWe/Info.plist
  ShallWe/ShallWe/Presentation/Auth/Model/GenderType.swift
  ShallWe/ShallWe/Presentation/Common/Components/CustomNavigationBar.swift
  ShallWe/ShallWe/Presentation/FAQ/Cell/FAQTableViewCell.swift
  ShallWe/ShallWe/Presentation/FAQ/Cell/ReasonForWithdrawalTableViewCell.swift
  ShallWe/ShallWe/Presentation/FAQ/Model/FAQType.swift
  ShallWe/ShallWe/Presentation/FAQ/View/AccountSettingsView.swift
  ShallWe/ShallWe/Presentation/FAQ/View/FAQView.swift
  ShallWe/ShallWe/Presentation/FAQ/View/WithdrawalView.swift
  ShallWe/ShallWe/Presentation/FAQ/ViewController/AccountSettingsViewController.swift
  ShallWe/ShallWe/Presentation/FAQ/ViewController/FAQViewController.swift
  ShallWe/ShallWe/Presentation/FAQ/ViewController/WithdrawalViewController.swift
  ShallWe/ShallWe/Presentation/Main/Category/ViewControllers/CategoryViewController.swift
Labels: 🌱 Feat, 🐶 나연
